server:
  port: 8080
spring:
  application:
    name: redisDemo
  datasource:
    name: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/redis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&tinyInt1isBit=false
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
